# Using numpy

Numpy is a library for the Python programming language. It adds support for large, multi-dimensional arrays and matrices. It has a large collection of mathematical functions to operate on these arrays. 

First we import the numpy-library, then we create an array and print it.

In [2]:
import numpy as np           #Import numpy library as a short name np
a = np.array([[1,2],[3,4]])  #Create an array 
print a                      #Print the Array

[[1 2]
 [3 4]]


Create 10 x 10 array full of ones and a random array:

In [6]:
b = np.ones((10,10))         
print b
c = np.random.random((5,5))
print c

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[[ 0.59710869  0.57054003  0.71197508  0.80508534  0.30290094]
 [ 0.06052442  0.74875549  0.59185483  0.75588652  0.54458034]
 [ 0.53533902  0.1538716   0.99503046  0.8259193   0.41193751]
 [ 0.29232844  0.27755668  0.73414257  0.22606308  0.70253809]
 [ 0.26782762  0.56768674  0.04236896  0.22760428  0.40025193]]


In [26]:
d = np.arange(50).reshape(5,10)       #Create 1, 2, 3, .... matrix (10 x 5) starting at 0
print d
e = np.arange(1,51).reshape(5,10)     #Create 1, 2, 3, ...  matrix (10 x 5) starting at 1
print e
print e.shape                         #Print shape of the matrix

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
(5, 10)


In [25]:
f = e[1, :]                         #Taking the second row
print f
g = e[:, 2]                         #Taking the second column
print g

[11 12 13 14 15 16 17 18 19 20]
[ 3 13 23 33 43]


In [28]:
print e
even_matrix = (e % 2 == 0)          #Check if the number is even in the matrix
print even_matrix

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
[[False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]]


In [29]:
print(d+e)                        #Count two matrices together

[[ 1  3  5  7  9 11 13 15 17 19]
 [21 23 25 27 29 31 33 35 37 39]
 [41 43 45 47 49 51 53 55 57 59]
 [61 63 65 67 69 71 73 75 77 79]
 [81 83 85 87 89 91 93 95 97 99]]


In [30]:
print (d*e)                      #Multiply matrices

[[   0    2    6   12   20   30   42   56   72   90]
 [ 110  132  156  182  210  240  272  306  342  380]
 [ 420  462  506  552  600  650  702  756  812  870]
 [ 930  992 1056 1122 1190 1260 1332 1406 1482 1560]
 [1640 1722 1806 1892 1980 2070 2162 2256 2352 2450]]
